### ISSUE TITLE
[FEATURE] DataFrame In -> [] -> DataFrame Out

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#258]
How about a DF wrapper around some sklearn classes which are useful? 

One of the thing which sklearn transformers does is that they take df as input but they returns the transformed result in numpy array format which are not in tabular format like DF and hence are hard to look and interpret and so we have to manually convert them to dataframe. 

But if we have DF wrappers around these sklearn classes( no matter they are transformers or feature selectors) then the user can stack them in a pipeline which works on the principle DF In  DF Out.  
(DFI-DFO)

Have a look at how I use them(The classes starting with DF are wraped around sklearn inbuilt classes and rest are custom): 

![DF_transformer](https://user-images.githubusercontent.com/32649388/71767345-7ae5b980-2f31-11ea-9295-f50ad9e2d05a.png)

My pipeline have 4 type of classes : 
     1. Some feature preprocessors
     2. Some feature transformers like DummyTransformer, DFPowerTransformer etc
     3. One feature expander, DFPolynomialFeatures
     4. One feature compressor, DFSelectKBest

But the beauty is everything is in a single pipeline, working on DFI-DFO ie., each class in this pipeline takes DF as input and passes transformed DF to next class in the pipeline. And the end result is df which is always handy as compare to numpy arrays.

 But this thing is not supported by sklearn natively. 

Here is how these wrappers look at very minimial level : 

    class DFSelectKBest(TransformerMixin):

    def __init__(self, k):
        self.k = k
        self.kbest = SelectKBest(k=k)

    def fit(self, X, y):
        self.kbest.fit(X, y)
        self.selected_indices = self.kbest.get_support(indices=True)
        self.selected_columns = [X.columns[i] for i in self.selected_indices]
        return self

    def transform(self, df):
        X = df.copy(deep=True)
        df_X = pd.DataFrame(self.kbest.transform(X), columns=self.selected_columns)
        return df_X

And once we are finished with all data science stuff we can either append an estimator at the end or can even wrap on outer pipeline having this X_transformer pipeline and an estimator and can then apply grid search like this, 

![grid_pipeline](https://user-images.githubusercontent.com/32649388/71767869-0746ab00-2f37-11ea-8d3f-d98ec9fbbd57.png)

**Comment by greatsharma** [comment]
Note, some of the classes in above pipeline is not much generic but some do :)

**Comment by koaning** [comment]
I have done some thinking about this topic. And I see three main downsides; 

- One downside of doing a lot of work in this area is that the pandas API is bound to change once v1.0 hits (and I prefer not to have to do an overhaul) and the sklearn API is bound to also make use of a named array in the future to allow for named features (and I prefer not to have to do an overhaul). 
- Also ... there are **so many** transformers for which it makes no sense to keep the pandas dataframe. Example; take a dataframe with 5 columns, reduce it down to three with PCA, what column names do we give to these three new columns? It is true that we've implemented a few transformers for dataframes but it is not the case that we consider dataframes first class citizens. 
- In the end, the models in scikit-learn expect a numpy array. The dataframe might be compatible in some instances. But if we wish to remain compatible then numpy arrays deserves the primary goal, dataframes are very much secondary to support.
- Taking every applicable transformer out there and redo-ing it just to make it df-in/df-out feels like a lot of repetition to have in the codebase, which will be a huge pain to maintain.

Instead, what might work is a meta-estimator. One that accepts a transformer as input and will enforce that the output remains a dataframe if it is passed in. I don't know how useful it will be since it can only work for a few transformers and the end user will need to really pay attention. 

The functionality might work something like; 

```
from sklego.meta import KeepDataFrame
from sklearn.preprocessing import StandardScaler 

df_selector = KeepDataFrame(estimator=StandardScaler) 
```

The `KeepDataFrame` only needs to be implemented once but can be used to wrap other transformers. This could work, but it will only work on the subset of transformers for which it makes sense to keep a dataframe.

Sidenote. The screenshot you provide, at least to me (and I am dyslexic), is confusing due to the information overload. Example; what does the variable `todo_X` stand for? Is it relevant to the point you're making or is it a detail?

**Comment by greatsharma** [comment]
The transformers not starting with DF are not generic and are specific to my work and the dataset I used. So todo_X belongs to that transformer that I created for that specific usecase/dataset. 
Everything starting with DF is generic because it is wraped around prebuilt sklearn classes.

I agree with the meta-estimator thing

**Comment by koaning** [comment]
@MBrouns any thoughts on the idea of `KeepDataFrame` as a meta estimator?

**Comment by MBrouns** [comment]
I've also played around with having a meta-transformer for keeping dataframes in and out, but there's some things I'm not sure of yet. My implementation looked something like this:

```

class DF(TransformerMixin, BaseEstimator):
    def __init__(self, base_transformer):
        self.base_transformer = base_transformer

    def fit(self, X, y=None):
        self.columns_ = X.columns
        self.base_transformer_ = clone(self.base_transformer).fit(X, y)
        self.output_shape_ = self.base_transformer_.transform(X).shape[1]
        
        return self

    def transform(self, X, y=None):
        check_is_fitted(self)
        return pd.DataFrame(self.base_transformer_.transform(X, y), columns=self.get_feature_names())

    def get_feature_names(self):
        try:
            return super().get_feature_names()
        except AttributeError:
            if self.columns_ is None:
                raise ValueError(f'DF of {self.base_transformer} was not fitted on a dataframe and'
                                 f'{self.base_transformer} does not implement get_feature_names')
            if len(self.columns_) != self.output_shape_:
                raise ValueError(f'DF of {self.base_transformer} was fitted on a dataframe with {len(self.columns_)} '
                                 f'columns while transformed dataframe had {self.output_shape_} columns and '
                                 f'{self.base_transformer} does not implement get_feature_names')

        return self.columns_

    


scaler = DF(StandardScaler()).fit(data)
scaler.transform(data)
```

It primarily relies on the `get_feature_names` of the BaseEstimator to figure out what the column names after transformations should be, but as that is not implemented on a lot of estimators it can fall back on the column names that were present during fitting as long as the shapes align. 

While it does seem to work there are a few gotcha's here and there that impact the usability quite a bit. If we want to go this route and actually make it useful, we should probably use `singledispatch` to retrofit some `get_feature_names` implementations on stuff like the `OneHotEncoder`. The `Pipeline` object is also one of those transformers that doesn't have a `get_feature_names` but which would be quite essential.

**Comment by greatsharma** [comment]
I like the idea of `singledispatch`. And I think we can for now implement  this for those which either have `get_feature_name` or those who keeps the df shape same.
Apart from that why you place `if self.columns_  is None `  doesn't it always evaluates to `False`. Is I am missing something?

**Comment by MBrouns** [comment]
ah yes, there should be a `if isinstance(X, pd.DataFrame)` in the `fit` before setting `self.columns_`

**Comment by greatsharma** [comment]
@MBrouns are we having eye on this?

**Comment by MBrouns** [comment]
I haven't been working on this, it's been rather busy with other things. I think I'm still open to having an implementation for this, but I'm not sure how useful this is if we only focus on transformers that keep the same shape or have `get_feature_names`. What could help is to have an overview of which transformers in sklearn do have these constraints and which don't
