### ISSUE TITLE
Redundant checking

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#263]
The current code of `_col_idx()` of `InformationFilter` is, 
```
def _col_idx(self, X, name):
    if isinstance(name, str):
        if isinstance(X, np.ndarray):
            raise ValueError("You cannot have a column of type string on a numpy input matrix.")
        return {name: i for i, name in enumerate(X.columns)}[name]
    return name
```
But all these `if` seems to be redundant because in
`self.col_ids_ = [v if isinstance(v, int) else self._col_idx(X, v) for v in self.cols]`  this function will be called only when the column names are `str` which makes the first `if` always `True`, and string column names are for DF only which makes the second `if` always `False` . So, we can just do,

```
def _col_idx(self, X, name):
   return {name: i for i, name in enumerate(X.columns)}[name]
```
but this has one more concern because every time we call `_col_idx` it will create the same dictionary again and again and for large # calls this is a lot repeated computation. Instead we can create it once and use any no. of times by this,

```
def _col_idx(self, X, name):
    if not hasattr(self, 'column_dict_'):
        self.column_dict_ = {name: i for i, name in enumerate(X.columns)}
    return self.column_dict_[name]
```

I worked on this and after these changes the behaviour remains the same.

If I am missing something please point, else I would like to make a PR

**Comment by MBrouns** [comment]
There's indeed something here that could be improved, let's walk through the changes

the `_col_idx` indeed only gets called with strings because of this if statement here: `[v if isinstance(v, int) else self._col_idx(X, v) for v in self.columns]` In terms of readability though I might actually suggest to remove the if statement from the comprehension into the `_col_idx` method, rather than the other way around. 

Indeed the method should only get called with string column names when an actual dataframe is passed, but since both are user input, it's easy to mess up. I would argue in favour of keeping the check for numpy arrays. 

I'm not sure the actual repeated generation of the dictionary matters all that much. `X.columns` is an attribute lookup and it's O(N*M) where N is the number of columns we want to filter out and M the number of columns in the dataframe. I expect both to be small in general and keeping track of that additional state in the class would more easily lead to confusion.

 
I would probably propose changing it to this:
```
    def _col_idx(self, X, name):
        if isinstance(name, int):
            return name

        if isinstance(X, np.ndarray):
            raise ValueError("You cannot have a column of type string on a numpy input matrix.")

        return {name: i for i, name in enumerate(X.columns)}[name]
```
and changing the call in fit to `self.col_ids_ = [self._col_idx(X, v) for v in self.columns]`

**Comment by greatsharma** [comment]
@MBrouns I agree with moving if statement from the comprehension into the _col_idx method, but I still unable to understand what's the need of `if isinstance(X, np.ndarray)` because all the `types` checking are done in `_check_coltype()` and infact that's why we are having a separate function for that. All such cases had been handed in these lines of `_check_coltype()`
```
if isinstance(col, str):
    if isinstance(X, np.ndarray):
        raise ValueError(f"column {col} is a string but datatype receive is numpy.")
```

One more thing I just again gone through the code and found that in this class we are having both `self.columns` and `self.cols`  but only one is needed and infact `self.columns` is never used.

Point if I am missing something.

**Comment by greatsharma** [comment]
@MBrouns any update on this?

**Comment by MBrouns** [comment]
> @MBrouns I agree with moving if statement from the comprehension into the _col_idx method, but I still unable to understand what's the need of if isinstance(X, np.ndarray) because all the types checking are done in _check_coltype() and infact that's why we are having a separate function for that. All such cases had been handed in these lines of _check_coltype()

fair enough, I'm currently wondering though whether we need `_check_coltype` at all. If we do proper error handling in the `_col_idx` we could probably do without it and reduce the complexity of the code a bit

**Comment by greatsharma** [comment]
> > @MBrouns I agree with moving if statement from the comprehension into the _col_idx method, but I still unable to understand what's the need of if isinstance(X, np.ndarray) because all the types checking are done in _check_coltype() and infact that's why we are having a separate function for that. All such cases had been handed in these lines of _check_coltype()
> 
> fair enough, I'm currently wondering though whether we need `_check_coltype` at all. If we do proper error handling in the `_col_idx` we could probably do without it and reduce the complexity of the code a bit

`_col_idx` is called in `fit` only so we if do all error handling in `_col_idx` and remove `_check_coltype` then we miss checks of X in `transform`

**Comment by greatsharma** [comment]
@MBrouns did I miss something or there should be some other way around to correct it?

**Comment by MBrouns** [comment]
I think it is, in the end, the users' responsibility  to ensure the same form of data is passed to fit and transform, but it is of course possible to compute `col_ids_` in both `fit` and `transform` instead of having it be a fitted parameter on `self`
