### ISSUE TITLE
[DOCS] Adding references to the fairness section

### ISSUE THREAD

**Issue by jilljenn** [koaning/scikit-lego#280]
There should be more references in the [fairness](https://scikit-lego.readthedocs.io/en/latest/fairness.html) section of the documentation.

From your code I noticed:

- M. Zafar et al. (2017), Fairness Constraints: Mechanisms for Fair Classification

I guess there is also:

- M. Hardt, E. Price and N. Srebro (2016), Equality of Opportunity in Supervised Learning

**Comment by MBrouns** [comment]
Good catch, thanks! I just opened #281.

I'm not sure about adding the reference also to the EqualOpportunityClassifier as its current implementation is more an adaptation of Zafar et al.'s work to the equal opportunity score, rather than a proposed implementation of Hardt et al.  What do you think?

**Comment by jilljenn** [comment]
Gosh. You. Are. Fast. Great.

I was mainly referring to the docs themselves, so [this file](https://github.com/koaning/scikit-lego/blob/master/doc/fairness.ipynb). (By the way, I didn't know Sphinx was converting notebooks to documentation pages, was it through pandoc?)

**Comment by MBrouns** [comment]
Ah yes, we also use it there of course.

We use [nbsphinx](https://nbsphinx.readthedocs.io/en/0.5.1/) to parse `.ipynb` files and so far that's been working quite nicely for us

**Comment by MBrouns** [comment]
Fixed in #281
