### ISSUE TITLE
[BUG] ValueError in _RepeatingBasis

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#316]
I was running code coverage to see what code was not covered. 

![image](https://user-images.githubusercontent.com/1019791/78458623-275f4500-76b3-11ea-8d0c-f337768faf6d.png)

@RensDimmendaal it feels like the message in the error is off, would I be correct? If so, this might be a great beginner issue.

**Comment by RensDimmendaal** [comment]
Thanks for bringing that up.

I believe the error message is correct, but the if statement above is not. it should be `if X.shape[1] != 1`. X should have exactly one column, like the error message says. 

X should not be a one dimensional array, as the if statement says, but that check is not necessary because the `check_array` function above already does that.

Good beginner issue to fix and add a test indeed.

**Comment by sergiocalde94** [comment]
Hi! I would like to become a contributor.

If you want I can start with this issue :)

Is there any guide to become a contributor of this package?

If not, tell me and I will clone the repo and make a PR to you with the changes proposed by @RensDimmendaal

**Comment by koaning** [comment]
There should be a small contribution guide here: https://scikit-lego.readthedocs.io/en/latest/contribution.html. If that is "not enough" -> let us know here and we will help you (and feel free to add anything to the guide that is missing).

**Comment by sergiocalde94** [comment]
I didn't found a commit names standard or something like that, tell me if I have to change something!

**Comment by koaning** [comment]
It's merged!
