### ISSUE TITLE
[DOCS] additional EstimatorTransformer examples

### ISSUE THREAD

**Issue by lgpreston75** [koaning/scikit-lego#406]
I have found the EstimatorTransformer very useful for using yhat from a primary model as X in a secondary model. In my case it's been useful for predicting a very zero-inflated and skewed continuous y variable, whereby:

1. y is transformed
2. transformed y is predicted with X
3. transformed y is then used as an input to decision tree to map back to y

```
pipeline = Pipeline([

('rf_regressor', EstimatorTransformer(
    TransformedTargetRegressor(
        RandomForestRegressor(n_jobs=-1, n_estimators=140),
        transformer=KBinsDiscretizer(100, encode='ordinal', strategy='quantile'), check_inverse=False))),
    ('calibrator', DecisionTreeRegressor())
])    


pipeline.fit(X, y)
```

As discussed on twitter, I'm happy to put together a brief example in the form of a notebook. Is it possible for me to generate a toy dataset or is it preferable to use one of the internal ones?

**Comment by koaning** [comment]
If a toy dataset works best with your use-case then it's fine to use it. We've got some [datasets hosted](https://scikit-lego.readthedocs.io/en/latest/datasets.html) that you can consider but you don't have to. The main thing to keep in mind is to consider the "use case". That part of the intuition is usually when gets people to keep reading the docs.

If you're having trouble setting up the project locally. Here's some resources on [flake](https://calmcode.io/flake8/introduction.html), [pytest](https://calmcode.io/pytest/introduction.html), [makefiles](https://calmcode.io/makefiles/the-problem.html) and [precommit hooks](https://calmcode.io/pre-commit/the-problem.html).

**Comment by lgpreston75** [comment]
I have added an example below: 

Using the `EstimatorTransformer` we can also use the predicted output of a model as input into a second model. This is a useful way to deal with zero-inflated skewed data, which is a common occurence when predicting customer spend, and may be poorly fit by regression models. Chamberlain et al. (2017) [1] propose using a two-step approach where y is transformed into percentiles, predicted and then input into a secondary model with the non-transformed y to calibrate predictions.


[1] Chamberlain, Benjamin Paul, et al. "Customer lifetime value prediction using embeddings." Proceedings of the 23rd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining. 2017.

```
import numpy as np
import matplotlib.pylab as plt
from scipy.stats import skewnorm
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import KBinsDiscretizer

from sklego.meta import EstimatorTransformer

y = np.concatenate([skewnorm.rvs(n, size=1000), np.array([0]*100)])
X = np.random.uniform(0, 1,( n+100,2))
df = pd.DataFrame({"x1": X[:, 0], "x2": X[:, 1], "y": y})

pipeline = Pipeline([

('rf_regressor', EstimatorTransformer(
    TransformedTargetRegressor(
        RandomForestRegressor(),
        transformer=KBinsDiscretizer(100, encode='ordinal', strategy='quantile'), check_inverse=False))),
    ('dt_regressor', DecisionTreeRegressor())
])    



pipeline.fit(X, y)

pipeline.predict(X)
```

Are you happy with the style/content? If so, is it now a matter of me making a pull request?

**Comment by koaning** [comment]
@lgpreston75 looks like a good start 😄  

A few notes from my side. 

1. What is `zero-inflated skewed data`? I imagine many people don't know what it is (I'm not familiar). Could you explain what it is and how it relates to a practical/relevant/real-world problem? 
2. Can you maybe add a chart of the dataset? Not everybody might know about `skewnorm`. That might help explain the task that you're about to do. Especially a before/after image can really help people understand the operation that you're applying. 
3. The main users of this package will be folks from industry, not academia so it's fine to be less formal. A link to the paper is great though. 
4. Since the pipeline object is nested, it might be nice to explain what each piece does. It might help a lot of folks to emphasise what `TransformedTargetRegressor`and `KBinsDiscretizer` each do and how these piece together cause the thing you want. It might help to add an image -> I can help with that if you'd like.

As is, I'd say you can already make a PR and add the change to the relevant notebooks in the `docs` folder. What you're describing here sure seems like something that we can add to our docs. My only concern is that folks who are less familiar with jargon or the pydata stack might need some more explanations.

**Comment by koaning** [comment]
I'm closing this feature due to radio silence. Feel free to re-open if there's renewed interest.
