### ISSUE TITLE
IntervalEncoder == IsotonicRegression ?

### ISSUE THREAD

**Issue by dsleo** [koaning/scikit-lego#460]
Very nice toolbox !

It seems that `IntervalEncoder` is essentially an isotonic regression. It is available in scikit-learn ([here](https://scikit-learn.org/stable/modules/generated/sklearn.isotonic.IsotonicRegression.html)), and the implementation doesn't rely on cvpx, and rather uses pool adjacent violators algorithm - which has O(n) complexity.

... but perhaps I'm missing something ?

**Comment by koaning** [comment]
There's a few differences. 

- If you go to the docs [here](https://scikit-lego.netlify.app/preprocessing.html?highlight=intervalencoder#Monotonic-Encoding) you'll see that the encoder is also capable of generating non-monotonic features. 
- Our method cuts the interval into chunks upfront. The monotonic regressor will try to make the best fit, but it is free in when to jump up/down. Our method is constrained by how many chunks you propose. 
- Since the interval encoder is a transformer, it can be processed further. You might want to use the output as an input for a polynomial featurizer. 

The interval encoder, originally, was planned to also have variants like `"up-down-up"` and `"down-up-down"`. The idea here is that wage typically increases with age, up to a certain point, after which it goes down again. We haven't implemented this encoder yet, but the goal of this component is to have a place where we might be able to add such features as well.

**Comment by dsleo** [comment]
Thanks for the quick reply.

I only meant for the increasing/decreasing method of the IntervalEncoder, but what you are saying makes sense. Specially to use it as transformer further down.
