### ISSUE TITLE
[DOCS] log_step and load_chicken unexpected keyword arguments

### ISSUE THREAD

**Issue by TremaMiguel** [koaning/scikit-lego#469]
While running the tutorial [Logging in Method chaining](https://scikit-lego.readthedocs.io/en/latest/pandas_pipeline.html?highlight=log_step#Logging-in-method-chaining) with `sklego==0.6.7`, got a `TypeError` with the functions `log_step` and `load_chicken`.

```python
from sklego.datasets import load_chicken
from sklego.pandas_utils import log_step
chickweight = load_chicken(give_pandas=True)
>>> TypeError: load_chicken() got an unexpected keyword argument 'give_pandas'

...

@log_step(level=logging.DEBUG)
def remove_dead_chickens(chickweight):
    dead_chickens = chickweight.groupby('chick').size().loc[lambda s: s < 12]
    return chickweight.loc[lambda d: ~d['chick'].isin(dead_chickens)]
>>> TypeError: log_step() got an unexpected keyword argument 'level'
```

**Comment by koaning** [comment]
That's ... strange. Let me investigate.

**Comment by koaning** [comment]
Yep, this is a documentation bug. 

It seems like we turned off automated testing on our docs a while ago which is why this didn't get caught. I can confirm that the API description for [load_chickweight](https://scikit-lego.netlify.app/api/datasets.html#sklego.datasets.load_chicken) and [log_step](https://scikit-lego.netlify.app/api/pandas_utils.html#sklego.pandas_utils.log_step) are indeed correct but the notebooks are lagging. 

Will fix it right away and I'll also rethink our testing strategy. I don't like running very heavy test scripts (machine learning is kind of heavy to run at *every* commit) but it's a shame that this didn't get caught. Sorry about that!

**Comment by koaning** [comment]
The fix is deployed, once the tests are green I'll also merge the update into main. 

Again, sorry for that. The docs should've been better.

**Comment by TremaMiguel** [comment]
Thanks for the quick reply @koaning
