### ISSUE TITLE
Time series to supervised

### ISSUE THREAD

**Issue by PARODBE** [koaning/scikit-lego#549]
Hi,

First of all, thank you for this so useful library. I have a question since I just came across with your library. If you want convert the typical time series problem to supervised (input and output data are continuos), something like this: https://machinelearningmastery.com/convert-time-series-supervised-learning-problem-python/

Do you have any function or proposal for this?

Thanks!
Pablo

**Comment by koaning** [comment]
While this library does feature some tools for [timeseries-like tasks](https://scikit-lego.netlify.app/preprocessing.html?highlight=timeseries), it's not the main focus. Other projects like [sktime](https://www.sktime.org/en/stable/) might be closer to your interests. I want to be careful with adding timeseries features to this library, mainly because it feels like these should belong to other libraries the specialize more towards the timeseries domain. 

Will close the issue, as it doesn't seem related to the current state of the library.
