### ISSUE TITLE
Broken Deployment

### ISSUE THREAD

**Issue by KulikDM** [koaning/scikit-lego#612]
Hi @koaning, was just running my own github actions which failed. I traced it back to here (ModuleNotFoundError: No module named 'sklego.meta'). I saw that there was a recent release  (0.7.1) and downloaded the tarball. When I checked inside it seems like all the folders besides data are missing from the sklego folder.  Hope the issue is nothing too serious.

**Comment by koaning** [comment]
Oh dear. That might have been me. Thanks for reporting it @KulikDM, will have a look right away.

**Comment by koaning** [comment]
That's very weird, the same command that I've used for 5+ years now no longer includes the submodule. I made another release, to test if I had skipped a command, but same result. 

As a fix for now I've decided to yank v0.7.1 and v0.7.2 so that when folks install the most recent it will at least be a version with the meta submodule. In the meantime that means it won't break builds for folks while we figure out what's going on here. 

Sorry about this!

**Comment by KulikDM** [comment]
You are a really champ @koaning ! Thanks for addressing this so quickly and hope that you find what's happening with the publish command. All the best!

**Comment by koaning** [comment]
It wasn't just me, @FBruzzesi was the one who found the fix!

**Comment by KulikDM** [comment]
Thanks @FBruzzesi !
