### ISSUE TITLE
[BUG] Error when calling predict_proba with GroupedPredictor using shrinkage and global model

### ISSUE THREAD

**Issue by cerlymarco** [koaning/scikit-lego#616]
When trying to generate probabilities calling `predict_proba` from a fitted instance of `GroupedPredictor` with `shrinkage` not None and `use_global_model=True` the following error is generated:

<img width="582" alt="image" src="https://github.com/koaning/scikit-lego/assets/36955807/9db77ec8-17f2-449e-8092-835cbfc32ea6">

Code to reproduce the error:

<img width="358" alt="image" src="https://github.com/koaning/scikit-lego/assets/36955807/373d12bf-ce45-4fe8-af48-c201a6c9e33e">

```
import sklearn
import sklego
from sklego.datasets import load_hearts
from sklearn.linear_model import LogisticRegression
from sklego.meta import GroupedPredictor

## sklego.__version__   0.7.4
## sklearn.__version__  1.0.2

df_hearts = load_hearts(as_frame=True)
model = GroupedPredictor(
    LogisticRegression(max_iter=1000), groups=['sex'],
    use_global_model=True, shrinkage="relative",
).fit(df_hearts.drop(columns=['thal','target']), df_hearts['target'])

preds = model.predict_proba(df_hearts.drop(columns=['thal','target']))
```

**Comment by FBruzzesi** [comment]
Hey @cerlymarco, thanks for reporting this bug. I can replicate the issue and will take a closer look.

My first impression is that shrinkage was intended for regression problems only, as running `.predict(...)` with the same data you provided will yield values that are not classes.

**Comment by cerlymarco** [comment]
Hi @FBruzzesi, thanks for your reply! That seems reasonable. If that is the case, an error/warning may be raised when a classifier (an estimator with predict_proba method) is provided with shrinkage enabled. Otherwise, a proper shrinkage method for probabilities could be implemented

**Comment by FBruzzesi** [comment]
Hey @cerlymarco , as you can see this issue was mentioned in a few places. Just to add some description to each of those:

- [`GroupedPredictor` refactoring](https://github.com/koaning/scikit-lego/pull/618) was a first attempt to fix the issue reported here, as well as expanding the functionalities. Since this was getting a bit messy we decided to follow another approach, which led us to the following two points.
- [`GroupedPredictor` patch](https://github.com/koaning/scikit-lego/pull/619) follows your suggestion and raises an error if shrinkage is used in combination with a classification task. This is a somewhat breaking change which is already in the `main` branch.
- In [`HierarchicalPredictor` and `HierarchicalTransformer`](https://github.com/koaning/scikit-lego/issues/620) we set up the discussion for how to deal with that as well as adding other features to meta estimators that are somewhat similar to `Grouped*` ones.
  - I don't want to make promises, but you could expect `HierarchicalPredictor` (or even better a `HierarchicalClassifier`) that works with classification tasks and shrinkage to come fairly soon
