### ISSUE TITLE
[DOCS] add guide for sklego.pipeline.DebugPipeline

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#71]
Not every user will appreciate python logging so it might make sense to have a document in the documentation that gives an example of how a `DebugPipeline` might allow you to discover a bug.

**Comment by CorXccelerated** [comment]
Real life idea, I just got from Kay who had an error in his Pipeline. @kayhoogland: Can you add what I am missing here?

During modelling the rows where dropped if a specific column had None/null values. This (by accident) also happens when predicting, meaning that an error was thrown because the input into predict had a different number of rows then the output, while these should match. With a (simple) log statements that shows the shape of the numpy.array / pandas.dataframe this error can easily be spotted.

**Comment by koaning** [comment]
I've moved the notebook to sphinx last friday. Will close this for now. Feel free to make changes to the notebook for extra clarity though.
