### ISSUE TITLE
[Question] Pull request for scikit-learn

### ISSUE THREAD

**Issue by tomderuijter** [koaning/scikit-lego#82]
Hi, love the idea. Are you planning on submitting (parts of) this work as a pull request to scikit-learn as well? If so, which ones?

**Comment by koaning** [comment]
This is more up to the people over at sklearn to decide. I've not reached out to them yet and I think it might be wise to have people try out new things here first. 

SKlearn is a serious project with *many* people depending on it. The hope of this project (besides being a teaching outlet for me personally) is to explore what sklearn pipelines can do by allowing for more experimentation. It seems very plausible that there is a need for features that sklearn should perhaps not support. 

This doesn't mean we can't send things their way, but this is not the end goal. Especially since this project has *just* started.

**Comment by koaning** [comment]
Oh and also, this is still relevant to mention: https://pydata.org/amsterdam2019/cfp/. Sponsorships and CFPs are still welcome.

**Comment by koaning** [comment]
Since no more messages were posted here I'll close the discussion.
